services:
  go_vault:
    container_name: go_vault
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "54625:54625"
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=
    networks:
      - homelabs

networks:
  homelabs:
    external: true